#!/usr/bin/env bash
# Update package lists and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
sudo sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Nginx installation and configuration completed."
