#!/usr/bin/env bash
# This script permanently redirect to another page

sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me http://devfelz.tech permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sudo service nginx restart
