#!/usr/bin/env bash
# A script to configure Nginx server so that /redirect_me is redirecting to another page.

# Check if script is running with root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run with sudo or as root" 1>&2
    exit 1
fi

# Update package lists and install nginx
apt-get update
apt-get -y install nginx

# Allow HTTP traffic through UFW
ufw allow 'Nginx HTTP'

# Start Nginx service
service nginx start

# Create index file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to redirect /redirect_me
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx to use custom 404 page
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart

