#!/usr/bin/env bash

# Script: install_load_balancer.sh
# Description: Installs and configures HAProxy as a load balancer
# Author: Dennis Makaka
# Date: April 1, 2024

echo -e "Updating and performing minor checks...\n"

# Function to check and install a package if not already installed
function install() {
    command -v "$1" &> /dev/null

    # Check if the package is installed
    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up some configurations.\n"

# Backup the default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Define the new HAProxy server configuration
server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 520760-web-01 100.26.151.18 check
    server 520760-web-02 35.175.130.19 check
"

# Apply the new HAProxy server configuration
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "Configured - Roundrobin On web-01 & web-02"

# Start or restart the HAProxy service based on its status
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

